# Generated by Django 4.2 on 2025-08-12 04:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mammoth_bar', '0003_remove_register_id_register_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('kakao_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
